name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main  # ya master, agar aapki default branch master ho

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload website
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # yahaan aapke index.html wali directory ka path

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
